theme: jekyll-theme-midnight
title: Ben's Corner
google_analytics: UA-89444199-1
linkedin_url: https://www.linkedin.com/in/benjamin-kane
stackoverflow_url: https://stackoverflow.com/users/2958070/ben
