theme: jekyll-theme-midnight
title: Ben's Corner
google_analytics: UA-89444199-1
linkedin_link: https://www.linkedin.com/in/benjamin-kane-b6682539
stackoverflow_link: https://stackoverflow.com/users/2958070/ben
